#!/usr/bin/env bash

source "$HOME/framework.sh"
AGENTFILES="$WORKSPACE/repos/agentfiles"

agentsmd-symlink() {
    local source="$AGENTFILES/agentsmd/$1"
    local target="$2"
    symlink "$source/AGENTS.md" "$target/AGENTS.md"
    symlink "$source/AGENTS.md" "$target/CLAUDE.md"
}

# setup scripts
symlink "$AGENTFILES/scripts/add-skill.sh" "$HOME/bin/add-skill"
symlink "$AGENTFILES/scripts/add-command.sh" "$HOME/bin/add-command"

# configs
symlink "$AGENTFILES/codex/config.toml" "$HOME/.codex/config.toml"

# global
agentsmd-symlink "global" "$HOME/.codex"
agentsmd-symlink "global" "$HOME/.claude"
agentsmd-symlink "vault" "$WORKSPACE/vault"

# repos
agentsmd-symlink "lgtm" "$WORKSPACE/repos/lgtm"
agentsmd-symlink "chatterbox" "$WORKSPACE/repos/chatterbox"

# global skills & commands
add-skill "$AGENTFILES/skills/commit"
add-command "$AGENTFILES/commands/commit"
add-command "$AGENTFILES/commands/start-day"