#!/usr/bin/env bash

source "$HOME/framework.sh"
AGENTFILES="$WORKSPACE/repos/agentfiles"

agentsmd-symlink() {
    local source="$$AGENTFILES/agentsmd/$1"
    local target="$2"
    symlink "$source/AGENTS.md" "$target/AGENTS.md"
    symlink "$source/AGENTS.md" "$target/CLAUDE.md"
}

# vault
agentsmd-symlink "vault" "$WORKSPACE/vault"

# repos
agentsmd-symlink "lgtm" "$WORKSPACE/repos/lgtm"
agentsmd-symlink "chatterbox" "$WORKSPACE/repos/chatterbox"
